variables:
  authkey: $(auth_key)

trigger:
- azure-pipelines

pool:
  vmImage: 'macos-10.15'


steps:

- script: |
   mkdir -p android/app/build/outputs/apk/release
  displayName: 'Create path'


- script: |
    echo "$(Build.buildId)" > android/app/build/outputs/apk/release/app-release.apk
  displayName: 'Create APK'

- task: CopyFiles@2
  displayName: 'Copy APK file'
  inputs:
    SourceFolder: android/app/build/outputs/apk/release
    Contents: 'app-release.apk'
    TargetFolder: '$(build.artifactstagingdirectory)/ffh_$(Build.BuildID).apk'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true


- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: './DevOps/upload_apk.bash'
    arguments: $(authkey)
    failOnStderr: true

